spring:
    application:
        name: demo
    # 数据库相关配置
    datasource:
        # 目前手头的机器和数据库不在同一区域，不太好通过内网访问，暂用外网方式连接真实场景是需要通过内网连接的！！！ TODO
        url: jdbc:mysql://gz-cdb-97gj1jgv.sql.tencentcdb.com:24122/mic_test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
        username: mic
        password: micMIC123$$$
        driver-class-name: com.mysql.cj.jdbc.Driver
# 启动端口
server:
  port: 9999

mybatis:
  configuration:
    # 表中字段名与Bean字段名转换
    map-underscore-to-camel-case: true

# openapi 相关配置
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /index.html
  packages-to-scan: com.hongruxu.demo.controller

management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'