spring:
    application:
        name: demo
    # 数据库相关配置
    datasource:
        # 此处为调试方便，直接将mysql开通了外网并通过外网连接，真实场景是需要通过内网连接的！！！ TODO
        url: jdbc:mysql://gz-cdb-97gj1jgv.sql.tencentcdb.com:24122/mic_test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
        username: mic
        password: micMIC123$$$
        driver-class-name: com.mysql.cj.jdbc.Driver
# 启动端口
server:
  port: 9999

# openapi 相关配置
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/index.html
  packages-to-scan: com.hongruxu.demo.controller