# 配置 prometheus拉取数据
global:
  scrape_interval: 15s
  evaluation_interval: 15s
 
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot-demo'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['10.0.20.9:9999']
        labels:
          nodename: 'app-demo'